### ISSUE TITLE
npm install and start doesnt work

### ISSUE THREAD

**Issue by RhochR** [yonixw/r-place-selfhosted-ui#1]
I tried `npm install` it and it gives me this error:
``` sh
npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\myuser\Desktop\rplace/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\myuser\Desktop\rplace\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
I am running this on windows 10.

**Comment by yonixw** [comment]
Here is what worked for me in windows, I gonna update the read me just to be sure:

Please download latest commit again, I updated with latest node fix for react

Open 2 command lines, 1 for server and 1 for client
* Client:
    * `git clone https://github.com/yonixw/r-place-selfhosted-ui`
    * `cd r-place-selfhosted-ui`
    *  `yarn install` (and not npm install)
    *  `yarn start` - will start react in `localhost:3000`
         *  If you have old node (before v18), run: `yarn startBefore16`
* Server:
    * `git clone https://github.com/yonixw/r-place-selfhosted-server`
    * `cd r-place-selfhosted-server`
    *  `yarn install` (and not npm install)
    *  `yarn start` - will start express in `localhost:8080`

And using this setup, to play, open in browser this url:
`http://localhost:3000/?server=ws://localhost:8080/websockets`

Hope It solved it.

Note 1: On the first server start, you will get error that no previous disk save was found. Just ignore it:
![image](https://github.com/yonixw/r-place-selfhosted-ui/assets/5826209/b8af54bb-dcb3-4447-b6dd-4d880a015636)


Note 2: the temporary disk save is in `C:\tmp` :
![image](https://github.com/yonixw/r-place-selfhosted-ui/assets/5826209/02515e7c-d01f-45a6-b09c-a23865373e37)
